[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200

[[redirects]]
  from = "/api/admins"
  to = "/.netlify/functions/admins"
  status = 200
